<a href="https://colab.research.google.com/github/lee1201zxc/study/blob/main/Python/1_3_PyTorch_Tutorial_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# M2177.003100 Deep Learning Assignment 0<br> Part 3. PyTorch Tutorial

In [1]:
# only colab user!
!pip uninstall torch -y
!pip install torch torchvision torchaudio


Found existing installation: torch 2.10.0+cpu
Uninstalling torch-2.10.0+cpu:
  Successfully uninstalled torch-2.10.0+cpu
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 915.7/915.7 MB 1.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 87.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 594.3/594.3 MB 792.4 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 88.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.0/88.0 MB 9.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 954.8/954.8 kB 47.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 706.8/706.8 MB 1.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.1/193.1 MB 5.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 50.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.6/63.6 MB 14.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 267.5/267.5 MB 4.3 MB/s eta 0:00:00
   ━━

In [1]:
import torch
print(torch.__version__)

2.10.0+cpu


Adapted by Haneul Pyeon from the IPython version of the PyTorch tutorial (https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html) by Soumith Chintala.


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

## Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

GPU사용해서 빠른 계산, 자동 미분, 신경망 라이브러리와 연결

numpy는 CPU전용이라 느림



In [ ]:
import torch

<div class="alert alert-info"><h4>Note</h4><p>An uninitialized matrix is declared,
    but does not contain definite known
    values before it is used. When an
    uninitialized matrix is created,
    whatever values were in the allocated
    memory at the time will appear as the initial values.</p></div>



Construct a 5x3 matrix, uninitialized:



In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[3.5138e+25, 4.5293e-41, 9.9444e+14],
        [4.5293e-41, 2.8141e+25, 4.5293e-41],
        [1.5687e-38, 0.0000e+00, 1.0201e+15],
        [4.5293e-41, 1.0200e+15, 4.5293e-41],
        [9.9416e+14, 4.5293e-41, 1.0528e+15]])


Construct a randomly initialized matrix:



In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3430, 0.8823, 0.9128],
        [0.6340, 0.5311, 0.0398],
        [0.4082, 0.8038, 0.6988],
        [0.7630, 0.0654, 0.2449],
        [0.3788, 0.8175, 0.1915]])


Construct a matrix filled zeros and of dtype long:



In [5]:
# dtype= 텐서에 들어갈 자료형 미리 지정
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [6]:
# 자료형 통일
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [7]:
# 기존 텐서 x를 기준으로 같은 device, layout유지하면서 텐서 생성
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)
# x랑 같은 모양으로 난수 채우기(평균 0, 표준편차 1로(정규분포))
# 모델 가중치 초기화시 처음에 사용
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.0069, -0.8290,  0.2192],
        [-0.3547, -2.0967, -0.7614],
        [-0.0768, -1.6173, -1.8512],
        [-1.8162, -0.2802,  0.4601],
        [-0.0324, -0.9386, -0.0572]])


Get its size:



In [8]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

## Operations

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.9316, -0.5076,  0.3808],
        [ 0.2545, -1.7187,  0.1050],
        [ 0.7605, -0.8181, -1.1765],
        [-1.4961,  0.1297,  1.0293],
        [ 0.6638, -0.8083,  0.6659]])


Addition: syntax 2



In [10]:
print(torch.add(x, y))

tensor([[ 0.9316, -0.5076,  0.3808],
        [ 0.2545, -1.7187,  0.1050],
        [ 0.7605, -0.8181, -1.1765],
        [-1.4961,  0.1297,  1.0293],
        [ 0.6638, -0.8083,  0.6659]])


Addition: providing an output tensor as argument



In [11]:
result = torch.empty(5, 3)
# 추가 파라미터 사용 가능
torch.add(x, y, out=result)
print(result)

tensor([[ 0.9316, -0.5076,  0.3808],
        [ 0.2545, -1.7187,  0.1050],
        [ 0.7605, -0.8181, -1.1765],
        [-1.4961,  0.1297,  1.0293],
        [ 0.6638, -0.8083,  0.6659]])


Addition: in-place



In [12]:
# adds x to y -> y+=x, 메모리 절약
y.add_(x)
print(y)

tensor([[ 0.9316, -0.5076,  0.3808],
        [ 0.2545, -1.7187,  0.1050],
        [ 0.7605, -0.8181, -1.1765],
        [-1.4961,  0.1297,  1.0293],
        [ 0.6638, -0.8083,  0.6659]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [13]:
print(x[:, 1])

tensor([-0.8290, -2.0967, -1.6173, -0.2802, -0.9386])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [14]:
# 정규분포 난수 생성
x = torch.randn(4, 4)
# 메모리는 그대로 두고 모양만 바꿈
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [15]:
x = torch.randn(1)
print(x)
# 텐서 안에 숫자 하나 꺼내기
print(x.item())

tensor([-0.4188])
-0.4187905490398407


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations (if the Torch Tensor is on CPU), and changing one will change
the other.

## Converting a Torch Tensor to a NumPy Array



In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
# a와 같은 메모리를 공유하는 numpy배열을 만듬
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [18]:
a.add_(1)
print(a)
# b도 같이 바뀜
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically



In [19]:
import numpy as np
a = np.ones(5)
# numpy 배열 a를 텐서로 바꿈(메모리 공유)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [2]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    # 텐서를 어디로 보낼지 지정, 쿠다로 보내서 텐서를 GPU에서 계산할 수 있게함
    device = torch.device("cuda")
    # GPU에서 생성(device=device여서)
    y = torch.ones_like(x, device=device)
    # CPU에 있던 x를 GPU로 보냄
    x = x.to(device)
    # x,y 둘다 GPU에 있어야 GPU 계산이 실행됨
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))


Autograd: Automatic Differentiation
===================================

Central to all neural networks in PyTorch is the ``autograd`` package.
Let’s first briefly visit this, and we will then go to training our
first neural network.


The ``autograd`` package provides automatic differentiation for all operations
on Tensors. It is a define-by-run framework, which means that your backprop is
defined by how your code is run, and that every single iteration can be
different.

Let us see this in more simple terms with some examples.

autograd -> 자동 미분 제공

정적인 그래프가 아닌 실행하면서 바뀌는 그래프 -> Pytorch특징




Tensor
--------

``torch.Tensor`` is the central class of the package. If you set its attribute
``.requires_grad`` as ``True``, it starts to track all operations on it. When
you finish your computation you can call ``.backward()`` and have all the
gradients computed automatically. The gradient for this tensor will be
accumulated into ``.grad`` attribute.

To stop a tensor from tracking history, you can call ``.detach()`` to detach
it from the computation history, and to prevent future computation from being
tracked.

To prevent tracking history (and using memory), you can also wrap the code block
in ``with torch.no_grad():``. This can be particularly helpful when evaluating a
model because the model may have trainable parameters with
``requires_grad=True``, but for which we don't need the gradients.

There’s one more class which is very important for autograd
implementation - a ``Function``.

``Tensor`` and ``Function`` are interconnected and build up an acyclic
graph, that encodes a complete history of computation. Each tensor has
a ``.grad_fn`` attribute that references a ``Function`` that has created
the ``Tensor`` (except for Tensors created by the user - their
``grad_fn is None``).

If you want to compute the derivatives, you can call ``.backward()`` on
a ``Tensor``. If ``Tensor`` is a scalar (i.e. it holds a one element
data), you don’t need to specify any arguments to ``backward()``,
however if it has more elements, you need to specify a ``gradient``
argument that is a tensor of matching shape.


.requires_grad=True로 설정하면 그 텐서에 수행되는 모든 연산을 추적.



Create a tensor and set ``requires_grad=True`` to track computation with it



In [3]:
'''
autograd -> 자동 미분 제공(gradient계산), 계산 과정 녹화
정적인 그래프가 아닌 실행하면서 바뀌는 그래프 -> Pytorch특징

requires_grad=True -> 그 텐서에 수행되는 모든 연산을 추적
계산 끝난 후, .backward()호출 시 모든 gradient가 자동 계산됨, gradient는 .grad에 저장됨
.detach()호출 시 추적 종료
with torch.no_grad(): 이 블록 안에서는 아예 연산 기록을 하지 않음, 모델 평가시 유용, 메모리 절약

Tensor + Function -> 계산 그래프 생성, 계산 순서?-> 자동 미분 시스템 핵심
.grad_fn -> 텐서가 어떤 연산으로 생성됐는지 가리키는 포인터, 역전파에 필수
.grad -> gradient 저장
텐서가 스칼라(원소 1개)면 .backward()에 인자가 필요 없음

예시 코드
x = torch.tensor(2.0, requires_grad=True)  # 추적 시작
y = x * x                                  # y = x^2
y.backward()                               # 미분 계산
print(x.grad)

'''
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


Do a tensor operation:



In [26]:
# y크기가 x크기에 자동으로 맞춰짐
y = x + 2
# 연산 과정 기록중이기에 grad_fn도 같이 나옴
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


``y`` was created as a result of an operation, so it has a ``grad_fn``.



In [27]:
print(y.grad_fn)

Do more operations on ``y``



In [34]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


``.requires_grad_( ... )`` changes an existing Tensor's ``requires_grad``
flag in-place. The input flag defaults to ``False`` if not given.



In [35]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
# 중간에 키면 그 시점 이후만 추적됨.
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


Gradients
---------
Let's backprop now.
Because ``out`` contains a single scalar, ``out.backward()`` is
equivalent to ``out.backward(torch.tensor(1.))``.



In [36]:
# 역전파
# out이 스칼라이기에 그냥 backward()가능, 여러값이면 gradient방향 지정해줘야함 ex)y.backward(torch.ones_like(y))
out.backward()

Print gradients d(out)/dx




In [38]:
# 모든 원소 gradient, 각 원소마다 구함
print(x.grad)

tensor([[9., 9.],
        [9., 9.]])


You should have got a matrix of ``4.5``. Let’s call the ``out``
*Tensor* “$o$”.
We have that $o = \frac{1}{4}\sum_i z_i$,
$z_i = 3(x_i+2)^2$ and $z_i\bigr\rvert_{x_i=1} = 27$.
Therefore,
$\frac{\partial o}{\partial x_i} = \frac{3}{2}(x_i+2)$, hence
$\frac{\partial o}{\partial x_i}\bigr\rvert_{x_i=1} = \frac{9}{2} = 4.5$.



You can also stop autograd from tracking history on Tensors
with ``.requires_grad=True`` either by wrapping the code block in
``with torch.no_grad():``



In [40]:
print(x.requires_grad)
print((x ** 2).requires_grad)

# 이 블록 안 에서는 추적 하지 않아서 False가 나옴
with torch.no_grad():
	print((x ** 2).requires_grad)

True
True
False


Or by using ``.detach()`` to get a new Tensor with the same
content but that does not require gradients:



In [43]:
print(x.requires_grad)
# 추적 중지
y = x.detach()
print(y.requires_grad)
# x,y가 완전히 같은가?
print(x.eq(y).all())

True
False
tensor(True)


**Read Later:**

Document about ``autograd.Function`` is at
https://pytorch.org/docs/stable/autograd.html#function




Neural Networks
===============

Neural networks can be constructed using the ``torch.nn`` package.

Now that you had a glimpse of ``autograd``, ``nn`` depends on
``autograd`` to define models and differentiate them.
An ``nn.Module`` contains layers, and a method ``forward(input)``\ that
returns the ``output``.


A typical training procedure for a neural network is as follows:

- Define the neural network that has some learnable parameters (or
  weights)
- Iterate over a dataset of inputs
- Process input through the network
- Compute the loss (how far is the output from being correct)
- Propagate gradients back into the network’s parameters
- Update the weights of the network, typically using a simple update rule:
  ``weight = weight - learning_rate * gradient``

Define the network
------------------

Let’s define this network:


torch.nn -> 신경망 만드는 패키지, autograd에 의존함(모델은 nn이 만들고 미분 계산은 autograd가함)

nn.Module -> 여러 층을 포함하고 forward메소드 가지고 있으며 입력을 받아 출력값을 반환함

###학습 과정

1. 학습 가능한 가중치 가진 신경망 정의

2. 데이터셋을 반복해서 읽음

3. 입력을 모델에 통과시킴

4. 출력이 정답과 얼마나 다른지 계산

5. gradient를 네트워크 파라미터에 전파(역전파)

6. 가중치 업데이트


In [4]:
import torch
# 신경망 레이어 모음
import torch.nn as nn
# 레이어 함수 버전(relu, softmax, cross_entropy같은거)
import torch.nn.functional as F

# 클래스 정의, nn.Module을 상속 받아야함.파라미터 자동 등록, GPU이용, autograd연결이 가능해짐
class Net(nn.Module):

    # 생성자
    # 모델 구조를 생성하고 파라미터 관리 시스템 작동
    # self -> 현재 생성 중인 객체 자신 -> net
    def __init__(self):
        # 부모 클래스 초기화, 부모는 nn.Module
        # 이거 안하면 파라미터 관리 시스템이 제대로 작동 안 함.(모델 작동 X)
        # super(현재 클래스, 현재 객체(net)), super ->상속 모듈(nn.Module), Net의 부모 클래스를 찾아라
        super(Net, self).__init__()
        # an affine operation: y = Wx + b
        # 선형 레이어(input 10차원, 출력 5차원)(밀집층임)
        self.linearss = nn.Linear(10, 5)

    # 입력이 모델 통과하는 경로 정의
    # x= 입력 데이터
    # output = net(input)이걸 쓰면 내부적으로 output = net.forward(input)이렇게됨
    def forward(self, x):
        # 생성자에서 만든 레이어 사용, 밀집층 통과시킴(5차원 나옴)
        x = self.linearss(x)
        # 레이어 통과한 결과 반환(모델 출력)(가중치와 bias값들)
        return x

# self -> 현재 생성 중인 객체 자신 -> net
# self.linear 에서 linear는 사용자가 임의 지정한 이름임
net = Net()
print(net)

Net(
  (linearss): Linear(in_features=10, out_features=5, bias=True)
)


You just have to define the ``forward`` function, and the ``backward``
function (where gradients are computed) is automatically defined for you
using ``autograd``.
You can use any of the Tensor operations in the ``forward`` function.

The learnable parameters of a model are returned by ``net.parameters()``



In [5]:
# net.parameters() -> 모델 안의 weight과 bias반환
params = list(net.parameters())
print(params)
# weight크기
print(params[0].size())
# bias크기
print(params[1].size())

[Parameter containing:
tensor([[-0.2775, -0.2795, -0.2362,  0.1262,  0.0262,  0.0759, -0.2486,  0.0498,
          0.0352, -0.2096],
        [ 0.1412, -0.0944,  0.1453,  0.0280, -0.2124,  0.1146,  0.0402,  0.1892,
         -0.2449,  0.1856],
        [-0.3109, -0.0919, -0.0903,  0.2213,  0.0301, -0.3014, -0.0325, -0.1541,
         -0.2906, -0.1446],
        [-0.2656,  0.2408, -0.0679, -0.0014,  0.0451, -0.2582, -0.2752, -0.0542,
         -0.1247,  0.0499],
        [ 0.2851,  0.2103, -0.1922,  0.0925, -0.1815,  0.1282,  0.1629, -0.2818,
          0.1722, -0.1639]], requires_grad=True), Parameter containing:
tensor([-0.0106,  0.2928, -0.1211,  0.2633,  0.0742], requires_grad=True)]
torch.Size([5, 10])
torch.Size([5])


Let's try a random 1x10 input.
Note: expected input size of this net is 10.

In [6]:
# 모델에 실제 데이터 넣어보기
input = torch.randn(1, 10)
# input이 모델에서 x에 해당함
print(input)
out = net(input)
# 밀집층 통과한 5개층
print(out)

tensor([[ 0.8335, -0.9779, -0.1677, -1.0385, -0.0090,  0.6966, -0.4083, -1.7443,
          1.4246,  0.2878]])
tensor([[-0.0028, -0.1108, -0.8888, -0.3173,  0.7565]],
       grad_fn=<AddmmBackward0>)


<div class="alert alert-info"><h4>Note</h4><p>``torch.nn`` only supports mini-batches. The entire ``torch.nn``
    package only supports inputs that are a mini-batch of samples, and not
    a single sample.

    For example, ``nn.Linear`` will take in a 2D Tensor of
    ``nSamples x input_size``.

    If you have a single sample, just use ``input.unsqueeze(0)`` to add
    a fake batch dimension.</p></div>

Before proceeding further, let's recap all the classes you’ve seen so far.

**Recap:**
  -  ``torch.Tensor`` - A *multi-dimensional array* with support for autograd
     operations like ``backward()``. Also *holds the gradient* w.r.t. the
     tensor.
  -  ``nn.Module`` - Neural network module. *Convenient way of
     encapsulating parameters*, with helpers for moving them to GPU,
     exporting, loading, etc.
  -  ``nn.Parameter`` - A kind of Tensor, that is *automatically
     registered as a parameter when assigned as an attribute to a*
     ``Module``.
  -  ``autograd.Function`` - Implements *forward and backward definitions
     of an autograd operation*. Every ``Tensor`` operation creates at
     least a single ``Function`` node that connects to functions that
     created a ``Tensor`` and *encodes its history*.

**At this point, we covered:**
  -  Defining a neural network
  -  Processing inputs

**Still Left:**
  -  Computing the loss and calling backward
  -  Updating the weights of the network

Loss Function
-------------
A loss function takes the (output, target) pair of inputs, and computes a
value that estimates how far away the output is from the target.

There are several different
`loss functions <https://pytorch.org/docs/nn.html#loss-functions>`_ under the
nn package .
A simple loss is: ``nn.MSELoss`` which computes the mean-squared error
between the input and the target.

For example:

### 번역

파이토치는 mini-batch만 지원함


이제 lose계산, 역전파, 가중치 업데이트 과정을 거쳐야함


In [7]:

output = net(input)
# target 랜덤 생성
target = torch.randn(5)  # a dummy target, for example
# numpy의 reshape랑 view랑 같다고 생각하셈
# target=torch.randn(1,5)로 해도 같음
target = target.view(1, -1)  # make it the same shape as output
# Loss 함수 지정
criterion = nn.MSELoss()
# Loss 계산
loss = criterion(output, target)
print(loss)

tensor(1.6497, grad_fn=<MseLossBackward0>)


when we call ``loss.backward()``, the whole graph is differentiated
w.r.t. the loss, and all Tensors in the graph that has ``requires_grad=True``
will have their ``.grad`` Tensor accumulated with the gradient.

For illustration, let us follow a few steps backward:



In [8]:
# loss를 만든 연산 정보
print(loss.grad_fn)  # MSELoss
# 이 연산 바로 이전에 연결된 연산들
# [0]첫번째연결노드, [0]실제 function 객체
print(loss.grad_fn.next_functions[0][0])  # Linear

Backprop
--------
To backpropagate the error all we have to do is to ``loss.backward()``.
You need to clear the existing gradients though, else gradients will be
accumulated to existing gradients.


Now we shall call ``loss.backward()``, and have a look at conv1's bias
gradients before and after the backward.



In [9]:
# 모든 파라미터의 gradient를 0으로 초기화
net.zero_grad()     # zeroes the gradient buffers of all parameters

print('linearss.bias.grad before backward')
print(net.linearss.bias.grad)

# loss를 weight와 bias에 대해 미분(기울기 계산), 각 파라미터의 .grad에 저장
loss.backward()

print('linearss.bias.grad after backward')
# loss를 줄이기 위해 bias를 얼마나 바꿔야하는지 값 있음.
print(net.linearss.bias.grad)

linearss.bias.grad before backward
None
linearss.bias.grad after backward
tensor([-0.1653,  0.0063,  0.0823, -0.8061,  0.7974])


Now, we have seen how to use loss functions.

**Read Later:**

  The neural network package contains various modules and loss functions
  that form the building blocks of deep neural networks. A full list with
  documentation is `here <https://pytorch.org/docs/nn>`_.

**The only thing left to learn is:**

  - Updating the weights of the network

Update the weights
------------------
The simplest update rule used in practice is the Stochastic Gradient
Descent (SGD):

     ``weight = weight - learning_rate * gradient``

We can implement this using simple Python code:

.. code:: python

    learning_rate = 0.01
    for f in net.parameters():
        f.data.sub_(f.grad.data * learning_rate)

However, as you use neural networks, you want to use various different
update rules.
To enable this, we built a small package: ``torch.optim`` that
implements all these methods. Using it is very simple:



In [10]:
import torch.optim as optim
# 1스텝

# create your optimizer
# SGD방식으로  net.parameters를 업데이트, learning rate=0.01
optimizer = optim.SGD(net.parameters(), lr=0.01)

# in your training loop:
optimizer.zero_grad()   # zero the gradient buffers
output = net(input)
loss = criterion(output, target)
loss.backward()
# 학습, 가중치 업데이트
'''
for param in net.parameters():
    param = param - lr * param.grad
'''
optimizer.step()    # Does the update

.. Note::

      Observe how gradient buffers had to be manually set to zero using
      ``optimizer.zero_grad()``. This is because gradients are accumulated
      as explained in the `Backprop`_ section.




Training a Classifier
=====================

This is it. You have seen how to define neural networks, compute loss and make
updates to the weights of the network.

Now you might be thinking,

What about data?
----------------

Generally, when you have to deal with image, text, audio or video data,
you can use standard python packages that load data into a numpy array.
Then you can convert this array into a ``torch.*Tensor``.

-  For images, packages such as Pillow, OpenCV are useful
-  For audio, packages such as scipy and librosa
-  For text, either raw Python or Cython based loading, or NLTK and
   SpaCy are useful

Specifically for vision, we have created a package called
``torchvision``, that has data loaders for common datasets such as
Imagenet, CIFAR10, MNIST, etc. and data transformers for images, viz.,
``torchvision.datasets`` and ``torch.utils.data.DataLoader``.

This provides a huge convenience and avoids writing boilerplate code.

For this tutorial, we will use the MNIST dataset.
It is a dataset of handwritten digits which is widely used in the field of machine learning.
It has the classes '0' to '9'.
The images in MNIST are of size 1x28x28, i.e. 1-channel images of 28x28 pixels in size.


Training an image classifier
----------------------------

We will do the following steps in order:

1. Load and normalizing the MNIST training and test datasets using
   ``torchvision``
2. Define a network
3. Define a loss function
4. Train the network on the training data
5. Test the network on the test data

## 1. Loading and normalizing MNIST

Using ``torchvision``, it’s extremely easy to load MNIST.



In [11]:
import torch
from torchvision import datasets, transforms

The output of torchvision datasets are PILImage images of range [0, 1].
We transform them to Tensors of normalized range [-1, 1].
<div class="alert alert-info"><h4>Note</h4><p>If running on Windows and you get a BrokenPipeError, try setting
    the num_worker of torch.utils.data.DataLoader() to 0.</p></div>



In [12]:
# Compose -> 여러 변환을 순서대로 적용하는 파이프라인
# ToTensor ->0~1범위로 스케일링
# Normalize -> mean,std값 정규화
transform=transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
    ])

# transform -> 전처리 적용
trainset = datasets.MNIST('./data', train=True, download=True,
                   transform=transform)
testset = datasets.MNIST('./data', train=False,
                   transform=transform)

100%|██████████| 9.91M/9.91M [00:00<00:00, 38.5MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 1.12MB/s]
100%|██████████| 1.65M/1.65M [00:00<00:00, 9.69MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 6.12MB/s]


In [13]:
# Training settings
batch_size = 64
test_batch_size = 1000
no_cuda = False
seed = 1
input_size = 28*28 # 784
num_classes = 10

use_cuda = not no_cuda and torch.cuda.is_available()

torch.manual_seed(seed)

device = torch.device("cuda" if use_cuda else "cpu")

# 데이터 준비를 병렬로해서 GPU가 쉬지 않게 함
# num_workers -> 0=메인 프로세스만 사용, 1이상=백그라운드에서 로딩
# pin_memory=True -> GPU학습시 메모리 복사 속도 향상
# 딕셔너리 형태임 그래서 뒤에 **
kwargs = {}
if use_cuda:
    kwargs.update({'num_workers': 1,
                   'pin_memory': True}
                 )

# DataLoader생성, 데이터를 배치 단위로 잘라서 제공하기 위함
# shffle=True -> 매 epoch마다 데이터 섞기
train_loader = torch.utils.data.DataLoader(dataset=trainset, batch_size=batch_size, shuffle=True, **kwargs)
test_loader = torch.utils.data.DataLoader(dataset=testset, batch_size=test_batch_size, shuffle=False, **kwargs)

## 2. Define a network

In this assignment, we will use logistic regression model

In [14]:
net = nn.Linear(input_size, num_classes)

net = net.to(device)

## 3. Define a Loss function and optimizer
Let's use a cross entropy loss and SGD with momentum.


In [15]:
import torch.optim as optim

criterion = nn.CrossEntropyLoss()
# momentnum -> 이전 방향 기억해서 관성처럼 이동
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

## 4. Train the network

This is when things start to get interesting.
We simply have to loop over our data iterator, and feed the inputs to the
network and optimize.



In [16]:
# training settings
epochs = 10
# 몇 스텝마다 로그를 출력할지
log_interval = 100
save_model = True

In [17]:
def train_epoch(model, device, train_loader, optimizer, criterion, epoch):
    # 모델을 학습 모드로 변경(Dropout활성화, BatchNorm학습 모드 적용)
    model.train()
    # batch_idx->현재 몇 번째 배치인지
    for batch_idx, (data, target) in enumerate(train_loader):
        #데이터를 올바른 디바이스(GPU)로 이동(둘이 같아야 함)
        data, target = data.to(device), target.to(device)
        #Flatten, data.size(0)-> batch크기
        #ex) (64,1,28,28) -> (64,784)
        data = data.view(data.size(0), -1)
        #그래디언트 초기화
        optimizer.zero_grad()
        #순전파, 계산 그래프 기록
        output = model(data)
        #손실계산하기
        loss = criterion(output, target)
        #역전파 과정
        loss.backward()
        #가중치 업데이트
        optimizer.step()
        #로그 출력
        if batch_idx % log_interval == 0:
            print(f'Train Epoch: {epoch} [{batch_idx * len(data)}/{len(train_loader.dataset)} '
                  f'({100. * batch_idx / len(train_loader):.0f}%)]\tLoss: {loss.item():.6f}')


In [19]:
def test(model, device, test_loader, criterion):
    # 모델을 평가모드로 전환
    model.eval()
    # 전체 손실 합계 저장
    test_loss = 0.0
    # 맞춘 개수 카운트
    correct = 0
    # gradient 계산X->메모리 절약
    with torch.no_grad():
        for data, target in test_loader:
            # 디바이스 이동
            data, target = data.to(device), target.to(device)
            # Flatten
            data = data.view(data.size(0), -1)
            #예측 = model.forward(data), 모델에 데이터 넣기,
            #output 값 -> 각 클래스 별 점수
            output = model(data)
            #배치 손실 누적
            #criterion(output, target)->현재 배치의 평균 loss
            #.itme()-> loss는tensor인데 이걸 그냥 숫자로 변환
            #data.size(0)->배치 크기(64), 나중에 전체 평균 구할때 배치 크기가 다르면 잘 못 구해짐(배치 사이즈 크든 작든 같은 영향임)
            test_loss += criterion(output, target).item() * data.size(0)
            #예측 라벨 뽑기
            #argnax->가장 큰 값의 인덱스 반환(가장 확률(점수) 높은 클래스), 각각의 데이터마다 여러개 pred=길이 64짜리 벡터
            #dim=1->가로방향(클래스 방향), keepdim=True->기본적으로 argmax는 차원을 줄이는데 target과 shape맞추기 위해씀
            pred = output.argmax(dim=1, keepdim=True)
            #맞은 개수 세기
            '''
            pred.shape    # (64, 1)
            target.shape  # (64,)
            둘이 달라서 맞춰야함 target.view_as(pred)로
            pred.eq()->각 원소 비교해서 같으면 True
            sum->이 배치에서 맞은 개수 총합
            correct에는 지금까지 돌면서 모든 데이터 맞은 개수가 들어감(한 배치만이 아닌)
            '''
            correct += pred.eq(target.view_as(pred)).sum().item()
    #전체 데이터 기준 평균 손실(앞에서 모든 샘플의 손실 구해놔서 전체 데이터 수로 나눔)
    test_loss /= len(test_loader.dataset)
    # loss,정확도 출력
    print(f'\nTest set: Average loss: {test_loss:.4f}, '
          f'Accuracy: {correct}/{len(test_loader.dataset)} '
          f'({100. * correct / len(test_loader.dataset):.2f}%)\n')


In [20]:
for epoch in range(1, epochs + 1):
    train_epoch(net, device, train_loader, optimizer, criterion, epoch)

test(net, device, test_loader, criterion)

Train Epoch: 1 [0/60000 (0%)]	Loss: 2.262465
Train Epoch: 1 [6400/60000 (11%)]	Loss: 0.843791
Train Epoch: 1 [12800/60000 (21%)]	Loss: 0.742740
Train Epoch: 1 [19200/60000 (32%)]	Loss: 0.458739
Train Epoch: 1 [25600/60000 (43%)]	Loss: 0.777921
Train Epoch: 1 [32000/60000 (53%)]	Loss: 0.528602
Train Epoch: 1 [38400/60000 (64%)]	Loss: 0.470827
Train Epoch: 1 [44800/60000 (75%)]	Loss: 0.452435
Train Epoch: 1 [51200/60000 (85%)]	Loss: 0.465062
Train Epoch: 1 [57600/60000 (96%)]	Loss: 0.450837
Train Epoch: 2 [0/60000 (0%)]	Loss: 0.509600
Train Epoch: 2 [6400/60000 (11%)]	Loss: 0.378704
Train Epoch: 2 [12800/60000 (21%)]	Loss: 0.409610
Train Epoch: 2 [19200/60000 (32%)]	Loss: 0.366250
Train Epoch: 2 [25600/60000 (43%)]	Loss: 0.428474
Train Epoch: 2 [32000/60000 (53%)]	Loss: 0.597014
Train Epoch: 2 [38400/60000 (64%)]	Loss: 0.410017
Train Epoch: 2 [44800/60000 (75%)]	Loss: 0.446861
Train Epoch: 2 [51200/60000 (85%)]	Loss: 0.522282
Train Epoch: 2 [57600/60000 (96%)]	Loss: 0.440842
Train Epoch:

Let's quickly save our trained model:



In [ ]:
if save_model:
    torch.save(net.state_dict(), "mnist_net.pt")